spring.application.name=transaction-service
server.port=${PORT:8080}

# Spring Datasource Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-primary}:${DB_PORT:5432}/${DB_NAME:banking}
spring.datasource.username=${DB_USER:banking_user}
spring.datasource.password=${DB_PASSWORD:banking_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Custom Domain & Node Properties
node.id=${NODE_ID:node-2}
node.role=${NODE_ROLE:PRIMARY}
wal.file-path=${WAL_PATH:/data/wal/transactions.wal}
monitor.url=${MONITOR_URL:http://monitor:8500}

# Actuator
management.endpoints.web.exposure.include=health,info
