spring.application.name=apigateway

resilience4j.circuitbreaker.instances.lb-calls.slidingWindowSize=10
resilience4j.circuitbreaker.instances.lb-calls.failureRateThreshold=50
resilience4j.circuitbreaker.instances.lb-calls.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.lb-calls.permittedNumberOfCallsInHalfOpenState=3
